'use client';

import {useRef,useState} from 'react';

type ExportCard={card_id:number,title:string,wikipedia_url:string};
type BatchRow={card_id:string,title:string,wikipedia_url:string,views_total:string,period_start:string,period_end:string,status:string,error:string};
type Progress={read:number,updated:number,skipped:number,errors:number,bytes:number,total:number};
const HEADER=['card_id','title','wikipedia_url','views_total','period_start','period_end','status','error'];
const csvCell=(value:unknown)=>'"'+String(value??'').replaceAll('"','""')+'"';

function parseCsvLine(line:string){const values:string[]=[];let current='',quoted=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'){if(quoted&&line[i+1]==='"'){current+='"';i++}else quoted=!quoted}else if(ch===','&&!quoted){values.push(current);current=''}else current+=ch}values.push(current);if(quoted)throw Error('Ligne CSV incomplète.');return values}

async function request<T=any>(view:string,params:Record<string,string>):Promise<T>{const url=new URL('/api/atlas',location.href);url.searchParams.set('view',view);for(const [key,value] of Object.entries(params))url.searchParams.set(key,value);const response=await fetch(url);const data=await response.json() as T&{error?:string};if(!response.ok)throw Error(data.error||'Export impossible.');return data}

export default function HistoricalViewsPanel(){
 const [busy,setBusy]=useState<'export'|'import'|''>(''),[file,setFile]=useState<File|null>(null),[progress,setProgress]=useState<Progress>({read:0,updated:0,skipped:0,errors:0,bytes:0,total:0}),[message,setMessage]=useState(''),[existing,setExisting]=useState<number|null>(null);
 const input=useRef<HTMLInputElement>(null),pause=useRef(false);
 async function exportCards(scope:'all'|'missing'='all'){if(busy)return;setBusy('export');setMessage('');pause.current=false;setProgress({read:0,updated:0,skipped:0,errors:0,bytes:0,total:0});let cursor=0,received=0,total=0;const parts:string[]=['\uFEFFcard_id,title,wikipedia_url\r\n'];try{while(!pause.current){const result:{cards:ExportCard[],total?:number,done?:number,hasMore:boolean}=await request('historicalExport',{after:String(cursor),scope});if(result.total!==undefined){total=scope==='missing'?result.total-(result.done??0):result.total;setExisting(result.done??null)}if(!result.cards.length)break;parts.push(...result.cards.map(card=>[card.card_id,card.title,card.wikipedia_url].map(csvCell).join(',')+'\r\n'));received+=result.cards.length;cursor=result.cards.at(-1)!.card_id;setProgress(p=>({...p,read:received,total}));if(!result.hasMore)break;await new Promise(resolve=>setTimeout(resolve,0))}if(pause.current){setMessage('Export interrompu. Relance le bouton pour recréer le fichier.');return}const url=URL.createObjectURL(new Blob(parts,{type:'text/csv;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download=scope==='missing'?'wikicartes-cartes-a-completer.csv':'wikicartes-cartes-existantes.csv';link.click();setTimeout(()=>URL.revokeObjectURL(url),60000);setMessage(`${received.toLocaleString('fr-FR')} cartes exportées.`)}catch(error){setMessage((error as Error).message)}finally{setBusy('')}}
 async function importViews(selected:File){if(busy)return;setBusy('import');setMessage('');pause.current=false;setProgress({read:0,updated:0,skipped:0,errors:0,bytes:0,total:selected.size});const reader=selected.stream().getReader(),decoder=new TextDecoder();let buffer='',columns:string[]|null=null,batch:BatchRow[]=[],read=0,bytes=0,updated=0,skipped=0,errors=0;const flush=async()=>{if(!batch.length)return;const response=await fetch('/api/atlas',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'historicalViewsBatch',rows:batch})});const result=await response.json() as {updated:number,skipped:number,errors:number,error?:string};if(!response.ok)throw Error(result.error||'Import interrompu.');updated+=result.updated;skipped+=result.skipped;errors+=result.errors;setProgress({read,updated,skipped,errors,bytes,total:selected.size});batch=[]};const consume=async(line:string)=>{if(!line.trim())return;const values=parseCsvLine(line.replace(/\r$/,''));if(!columns){columns=values.map((x,i)=>i===0?x.replace(/^\uFEFF/,''):x);if(columns.length!==HEADER.length||columns.some((x,i)=>x!==HEADER[i]))throw Error('Fichier attendu : CSV généré par wikicartes_historical_views.py.');return}if(values.length!==HEADER.length)throw Error(`Colonnes invalides à la ligne ${read+2}.`);batch.push(Object.fromEntries(columns.map((key,i)=>[key,values[i]])) as BatchRow);read++;if(batch.length===100)await flush()};try{while(!pause.current){const next=await reader.read();if(next.done){buffer+=decoder.decode();if(buffer.trim())await consume(buffer);break}bytes+=next.value.byteLength;buffer+=decoder.decode(next.value,{stream:true});let end=buffer.indexOf('\n');while(end!==-1){await consume(buffer.slice(0,end));buffer=buffer.slice(end+1);end=buffer.indexOf('\n')}if(bytes%262144<next.value.byteLength)setProgress({read,updated,skipped,errors,bytes,total:selected.size})}await flush();setProgress({read,updated,skipped,errors,bytes,total:selected.size});if(pause.current){setMessage('Import en pause. Tu peux reprendre avec le même fichier ; les lignes déjà enregistrées seront ignorées.')}else{setMessage(`${updated.toLocaleString('fr-FR')} cartes mises à jour · ${skipped.toLocaleString('fr-FR')} ignorées · ${errors.toLocaleString('fr-FR')} erreurs.`);const stats=await request('historicalExport',{after:'0'});setExisting(stats.done??null)}}catch(error){setMessage((error as Error).message+' Relance le même fichier pour reprendre.')}finally{await reader.cancel().catch(()=>{});setBusy('')}}
 return <section className="admin-panel historical-views-panel"><h2>Vues historiques</h2><p>Exporte les cartes déjà créées, calcule leurs vues Wikipédia depuis juillet 2015 avec le script Python, puis importe son fichier de résultats. Le cumul est conservé à côté des vues du dernier mois.</p><div className="wiki-actions"><button className="outline-button" disabled={!!busy} onClick={()=>exportCards()}>Exporter les cartes existantes</button><button className="ghost" disabled={!!busy} onClick={()=>exportCards('missing')}>Exporter les cartes à compléter</button><a className="outline-button" href="/atlas_historical_views.py" download="wikicartes_historical_views.py">Télécharger le script Python</a><button className="gold-button" disabled={!!busy} onClick={()=>input.current?.click()}>Importer les vues historiques</button><input ref={input} type="file" accept=".csv,text/csv" hidden onChange={e=>{const chosen=e.target.files?.[0];e.target.value='';if(chosen){setFile(chosen);importViews(chosen)}}}/>{busy&&<button className="ghost" onClick={()=>pause.current=true}>Mettre en pause</button>}{!busy&&file&&progress.bytes<file.size&&<button className="outline-button" onClick={()=>importViews(file)}>Reprendre</button>}</div><p className="small">Après l’export : <code>python wikicartes_historical_views.py wikicartes-cartes-existantes.csv</code>. Le script reprend automatiquement avec son fichier de suivi si tu relances la même commande. Ne change pas le nom du CSV exporté pendant le calcul.</p>{existing!==null&&<p>{existing.toLocaleString('fr-FR')} cartes possèdent déjà un cumul historique.</p>}{progress.total>0&&<><div className="wiki-progress"><div style={{width:Math.min(100,Math.round((busy==='export'?progress.read:progress.bytes)/progress.total*100))+'%'}}/><span>{Math.min(100,Math.round((busy==='export'?progress.read:progress.bytes)/progress.total*100))}% · {progress.read.toLocaleString('fr-FR')} cartes {busy==='export'?'exportées':'lues'}</span></div>{busy==='import'||progress.updated>0?<p>{progress.updated.toLocaleString('fr-FR')} mises à jour · {progress.skipped.toLocaleString('fr-FR')} ignorées · {progress.errors.toLocaleString('fr-FR')} erreurs</p>:null}</>}{message&&<p role="status">{message}</p>}</section>
}
